"""rename sql unit

Revision ID: 2b70eefd6bcd
Revises: dc4fba89f119
Create Date: 2024-11-03 10:32:38.832220

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b70eefd6bcd"
down_revision: Union[str, None] = "dc4fba89f119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "product_recipe_association", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "unit",
            existing_type=sa.VARCHAR(length=11),
            type_=sa.Enum("GRAM", "MILLILITER", name="unit"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "product_recipe_association", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "unit",
            existing_type=sa.Enum("GRAM", "MILLILITER", name="unit"),
            type_=sa.VARCHAR(length=11),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
