"""add sodium to product

Revision ID: 0c2419e45f21
Revises: ca9f4af0ff9d
Create Date: 2024-07-25 10:08:45.020226

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c2419e45f21"
down_revision: Union[str, None] = "ca9f4af0ff9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("sodium", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "sodium")
    # ### end Alembic commands ###
