"""add description and servings to recipe

Revision ID: 8d33bab41297
Revises: 0c2419e45f21
Create Date: 2024-07-27 08:58:06.663245

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d33bab41297"
down_revision: Union[str, None] = "0c2419e45f21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe", sa.Column("description", sa.String(), nullable=False)
    )
    op.add_column("recipe", sa.Column("servings", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "servings")
    op.drop_column("recipe", "description")
    # ### end Alembic commands ###
